#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Mar 12 15:56:53 +07 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_int_to_float_time_synth -key {Post-Synthesis:sim_1:Timing:tb_int_to_float} -tclbatch tb_int_to_float.tcl -view /home/theanhnp/RGBtoGRAY/tb_int_to_float_behav.wcfg -log simulate.log"
xsim tb_int_to_float_time_synth -key {Post-Synthesis:sim_1:Timing:tb_int_to_float} -tclbatch tb_int_to_float.tcl -view /home/theanhnp/RGBtoGRAY/tb_int_to_float_behav.wcfg -log simulate.log

